try {
    foo();
} catch (e) {
    console.error(e);
}
